/*
 * generated by Xtext 2.23.0
 */
package mars.rover.parser.antlr;

import com.google.inject.Inject;
import mars.rover.parser.antlr.internal.InternalRoverDSLParser;
import mars.rover.services.RoverDSLGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class RoverDSLParser extends AbstractAntlrParser {

	@Inject
	private RoverDSLGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalRoverDSLParser createParser(XtextTokenStream stream) {
		return new InternalRoverDSLParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Mission";
	}

	public RoverDSLGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(RoverDSLGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
