/*
 * generated by Xtext 2.23.0
 */
package mars.rover.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class RoverDSLAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("mars/rover/parser/antlr/internal/InternalRoverDSL.tokens");
	}
}
