/**
 * generated by Xtext 2.23.0
 */
package mars.rover.roverDSL;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EEnum;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see mars.rover.roverDSL.RoverDSLFactory
 * @model kind="package"
 * @generated
 */
public interface RoverDSLPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "roverDSL";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.rover.mars/RoverDSL";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "roverDSL";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  RoverDSLPackage eINSTANCE = mars.rover.roverDSL.impl.RoverDSLPackageImpl.init();

  /**
   * The meta object id for the '{@link mars.rover.roverDSL.impl.TasksImpl <em>Tasks</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see mars.rover.roverDSL.impl.TasksImpl
   * @see mars.rover.roverDSL.impl.RoverDSLPackageImpl#getTasks()
   * @generated
   */
  int TASKS = 0;

  /**
   * The feature id for the '<em><b>Missionlist</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TASKS__MISSIONLIST = 0;

  /**
   * The number of structural features of the '<em>Tasks</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TASKS_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link mars.rover.roverDSL.impl.MissionImpl <em>Mission</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see mars.rover.roverDSL.impl.MissionImpl
   * @see mars.rover.roverDSL.impl.RoverDSLPackageImpl#getMission()
   * @generated
   */
  int MISSION = 1;

  /**
   * The feature id for the '<em><b>Missiontype</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MISSION__MISSIONTYPE = 0;

  /**
   * The feature id for the '<em><b>Beginsentence</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MISSION__BEGINSENTENCE = 1;

  /**
   * The feature id for the '<em><b>Finalsentence</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MISSION__FINALSENTENCE = 2;

  /**
   * The feature id for the '<em><b>Forwardspeed</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MISSION__FORWARDSPEED = 3;

  /**
   * The feature id for the '<em><b>Reversespeed</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MISSION__REVERSESPEED = 4;

  /**
   * The feature id for the '<em><b>Turndirection</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MISSION__TURNDIRECTION = 5;

  /**
   * The feature id for the '<em><b>Safetyproperty</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MISSION__SAFETYPROPERTY = 6;

  /**
   * The feature id for the '<em><b>Objectdistance</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MISSION__OBJECTDISTANCE = 7;

  /**
   * The feature id for the '<em><b>Bordercolor</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MISSION__BORDERCOLOR = 8;

  /**
   * The feature id for the '<em><b>Lakelist</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MISSION__LAKELIST = 9;

  /**
   * The feature id for the '<em><b>Colorlist</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MISSION__COLORLIST = 10;

  /**
   * The feature id for the '<em><b>Measurelist</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MISSION__MEASURELIST = 11;

  /**
   * The feature id for the '<em><b>Flashingcolor</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MISSION__FLASHINGCOLOR = 12;

  /**
   * The feature id for the '<em><b>Timeout</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MISSION__TIMEOUT = 13;

  /**
   * The number of structural features of the '<em>Mission</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MISSION_FEATURE_COUNT = 14;

  /**
   * The meta object id for the '{@link mars.rover.roverDSL.impl.IntegerImpl <em>Integer</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see mars.rover.roverDSL.impl.IntegerImpl
   * @see mars.rover.roverDSL.impl.RoverDSLPackageImpl#getInteger()
   * @generated
   */
  int INTEGER = 2;

  /**
   * The feature id for the '<em><b>Integer</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INTEGER__INTEGER = 0;

  /**
   * The number of structural features of the '<em>Integer</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INTEGER_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link mars.rover.roverDSL.impl.ColorImpl <em>Color</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see mars.rover.roverDSL.impl.ColorImpl
   * @see mars.rover.roverDSL.impl.RoverDSLPackageImpl#getColor()
   * @generated
   */
  int COLOR = 3;

  /**
   * The feature id for the '<em><b>Color</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COLOR__COLOR = 0;

  /**
   * The number of structural features of the '<em>Color</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COLOR_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link mars.rover.roverDSL.MissionType <em>Mission Type</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see mars.rover.roverDSL.MissionType
   * @see mars.rover.roverDSL.impl.RoverDSLPackageImpl#getMissionType()
   * @generated
   */
  int MISSION_TYPE = 4;

  /**
   * The meta object id for the '{@link mars.rover.roverDSL.Colors <em>Colors</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see mars.rover.roverDSL.Colors
   * @see mars.rover.roverDSL.impl.RoverDSLPackageImpl#getColors()
   * @generated
   */
  int COLORS = 5;

  /**
   * The meta object id for the '{@link mars.rover.roverDSL.Safety <em>Safety</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see mars.rover.roverDSL.Safety
   * @see mars.rover.roverDSL.impl.RoverDSLPackageImpl#getSafety()
   * @generated
   */
  int SAFETY = 6;


  /**
   * Returns the meta object for class '{@link mars.rover.roverDSL.Tasks <em>Tasks</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Tasks</em>'.
   * @see mars.rover.roverDSL.Tasks
   * @generated
   */
  EClass getTasks();

  /**
   * Returns the meta object for the containment reference list '{@link mars.rover.roverDSL.Tasks#getMissionlist <em>Missionlist</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Missionlist</em>'.
   * @see mars.rover.roverDSL.Tasks#getMissionlist()
   * @see #getTasks()
   * @generated
   */
  EReference getTasks_Missionlist();

  /**
   * Returns the meta object for class '{@link mars.rover.roverDSL.Mission <em>Mission</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Mission</em>'.
   * @see mars.rover.roverDSL.Mission
   * @generated
   */
  EClass getMission();

  /**
   * Returns the meta object for the attribute '{@link mars.rover.roverDSL.Mission#getMissiontype <em>Missiontype</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Missiontype</em>'.
   * @see mars.rover.roverDSL.Mission#getMissiontype()
   * @see #getMission()
   * @generated
   */
  EAttribute getMission_Missiontype();

  /**
   * Returns the meta object for the attribute '{@link mars.rover.roverDSL.Mission#getBeginsentence <em>Beginsentence</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Beginsentence</em>'.
   * @see mars.rover.roverDSL.Mission#getBeginsentence()
   * @see #getMission()
   * @generated
   */
  EAttribute getMission_Beginsentence();

  /**
   * Returns the meta object for the attribute '{@link mars.rover.roverDSL.Mission#getFinalsentence <em>Finalsentence</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Finalsentence</em>'.
   * @see mars.rover.roverDSL.Mission#getFinalsentence()
   * @see #getMission()
   * @generated
   */
  EAttribute getMission_Finalsentence();

  /**
   * Returns the meta object for the containment reference '{@link mars.rover.roverDSL.Mission#getForwardspeed <em>Forwardspeed</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Forwardspeed</em>'.
   * @see mars.rover.roverDSL.Mission#getForwardspeed()
   * @see #getMission()
   * @generated
   */
  EReference getMission_Forwardspeed();

  /**
   * Returns the meta object for the containment reference '{@link mars.rover.roverDSL.Mission#getReversespeed <em>Reversespeed</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Reversespeed</em>'.
   * @see mars.rover.roverDSL.Mission#getReversespeed()
   * @see #getMission()
   * @generated
   */
  EReference getMission_Reversespeed();

  /**
   * Returns the meta object for the containment reference '{@link mars.rover.roverDSL.Mission#getTurndirection <em>Turndirection</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Turndirection</em>'.
   * @see mars.rover.roverDSL.Mission#getTurndirection()
   * @see #getMission()
   * @generated
   */
  EReference getMission_Turndirection();

  /**
   * Returns the meta object for the attribute '{@link mars.rover.roverDSL.Mission#getSafetyproperty <em>Safetyproperty</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Safetyproperty</em>'.
   * @see mars.rover.roverDSL.Mission#getSafetyproperty()
   * @see #getMission()
   * @generated
   */
  EAttribute getMission_Safetyproperty();

  /**
   * Returns the meta object for the containment reference '{@link mars.rover.roverDSL.Mission#getObjectdistance <em>Objectdistance</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Objectdistance</em>'.
   * @see mars.rover.roverDSL.Mission#getObjectdistance()
   * @see #getMission()
   * @generated
   */
  EReference getMission_Objectdistance();

  /**
   * Returns the meta object for the containment reference '{@link mars.rover.roverDSL.Mission#getBordercolor <em>Bordercolor</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Bordercolor</em>'.
   * @see mars.rover.roverDSL.Mission#getBordercolor()
   * @see #getMission()
   * @generated
   */
  EReference getMission_Bordercolor();

  /**
   * Returns the meta object for the attribute list '{@link mars.rover.roverDSL.Mission#getLakelist <em>Lakelist</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Lakelist</em>'.
   * @see mars.rover.roverDSL.Mission#getLakelist()
   * @see #getMission()
   * @generated
   */
  EAttribute getMission_Lakelist();

  /**
   * Returns the meta object for the attribute list '{@link mars.rover.roverDSL.Mission#getColorlist <em>Colorlist</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Colorlist</em>'.
   * @see mars.rover.roverDSL.Mission#getColorlist()
   * @see #getMission()
   * @generated
   */
  EAttribute getMission_Colorlist();

  /**
   * Returns the meta object for the attribute list '{@link mars.rover.roverDSL.Mission#getMeasurelist <em>Measurelist</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Measurelist</em>'.
   * @see mars.rover.roverDSL.Mission#getMeasurelist()
   * @see #getMission()
   * @generated
   */
  EAttribute getMission_Measurelist();

  /**
   * Returns the meta object for the containment reference '{@link mars.rover.roverDSL.Mission#getFlashingcolor <em>Flashingcolor</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Flashingcolor</em>'.
   * @see mars.rover.roverDSL.Mission#getFlashingcolor()
   * @see #getMission()
   * @generated
   */
  EReference getMission_Flashingcolor();

  /**
   * Returns the meta object for the containment reference '{@link mars.rover.roverDSL.Mission#getTimeout <em>Timeout</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Timeout</em>'.
   * @see mars.rover.roverDSL.Mission#getTimeout()
   * @see #getMission()
   * @generated
   */
  EReference getMission_Timeout();

  /**
   * Returns the meta object for class '{@link mars.rover.roverDSL.Integer <em>Integer</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Integer</em>'.
   * @see mars.rover.roverDSL.Integer
   * @generated
   */
  EClass getInteger();

  /**
   * Returns the meta object for the attribute '{@link mars.rover.roverDSL.Integer#getInteger <em>Integer</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Integer</em>'.
   * @see mars.rover.roverDSL.Integer#getInteger()
   * @see #getInteger()
   * @generated
   */
  EAttribute getInteger_Integer();

  /**
   * Returns the meta object for class '{@link mars.rover.roverDSL.Color <em>Color</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Color</em>'.
   * @see mars.rover.roverDSL.Color
   * @generated
   */
  EClass getColor();

  /**
   * Returns the meta object for the attribute '{@link mars.rover.roverDSL.Color#getColor <em>Color</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Color</em>'.
   * @see mars.rover.roverDSL.Color#getColor()
   * @see #getColor()
   * @generated
   */
  EAttribute getColor_Color();

  /**
   * Returns the meta object for enum '{@link mars.rover.roverDSL.MissionType <em>Mission Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Mission Type</em>'.
   * @see mars.rover.roverDSL.MissionType
   * @generated
   */
  EEnum getMissionType();

  /**
   * Returns the meta object for enum '{@link mars.rover.roverDSL.Colors <em>Colors</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Colors</em>'.
   * @see mars.rover.roverDSL.Colors
   * @generated
   */
  EEnum getColors();

  /**
   * Returns the meta object for enum '{@link mars.rover.roverDSL.Safety <em>Safety</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Safety</em>'.
   * @see mars.rover.roverDSL.Safety
   * @generated
   */
  EEnum getSafety();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  RoverDSLFactory getRoverDSLFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link mars.rover.roverDSL.impl.TasksImpl <em>Tasks</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see mars.rover.roverDSL.impl.TasksImpl
     * @see mars.rover.roverDSL.impl.RoverDSLPackageImpl#getTasks()
     * @generated
     */
    EClass TASKS = eINSTANCE.getTasks();

    /**
     * The meta object literal for the '<em><b>Missionlist</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TASKS__MISSIONLIST = eINSTANCE.getTasks_Missionlist();

    /**
     * The meta object literal for the '{@link mars.rover.roverDSL.impl.MissionImpl <em>Mission</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see mars.rover.roverDSL.impl.MissionImpl
     * @see mars.rover.roverDSL.impl.RoverDSLPackageImpl#getMission()
     * @generated
     */
    EClass MISSION = eINSTANCE.getMission();

    /**
     * The meta object literal for the '<em><b>Missiontype</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MISSION__MISSIONTYPE = eINSTANCE.getMission_Missiontype();

    /**
     * The meta object literal for the '<em><b>Beginsentence</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MISSION__BEGINSENTENCE = eINSTANCE.getMission_Beginsentence();

    /**
     * The meta object literal for the '<em><b>Finalsentence</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MISSION__FINALSENTENCE = eINSTANCE.getMission_Finalsentence();

    /**
     * The meta object literal for the '<em><b>Forwardspeed</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MISSION__FORWARDSPEED = eINSTANCE.getMission_Forwardspeed();

    /**
     * The meta object literal for the '<em><b>Reversespeed</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MISSION__REVERSESPEED = eINSTANCE.getMission_Reversespeed();

    /**
     * The meta object literal for the '<em><b>Turndirection</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MISSION__TURNDIRECTION = eINSTANCE.getMission_Turndirection();

    /**
     * The meta object literal for the '<em><b>Safetyproperty</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MISSION__SAFETYPROPERTY = eINSTANCE.getMission_Safetyproperty();

    /**
     * The meta object literal for the '<em><b>Objectdistance</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MISSION__OBJECTDISTANCE = eINSTANCE.getMission_Objectdistance();

    /**
     * The meta object literal for the '<em><b>Bordercolor</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MISSION__BORDERCOLOR = eINSTANCE.getMission_Bordercolor();

    /**
     * The meta object literal for the '<em><b>Lakelist</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MISSION__LAKELIST = eINSTANCE.getMission_Lakelist();

    /**
     * The meta object literal for the '<em><b>Colorlist</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MISSION__COLORLIST = eINSTANCE.getMission_Colorlist();

    /**
     * The meta object literal for the '<em><b>Measurelist</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MISSION__MEASURELIST = eINSTANCE.getMission_Measurelist();

    /**
     * The meta object literal for the '<em><b>Flashingcolor</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MISSION__FLASHINGCOLOR = eINSTANCE.getMission_Flashingcolor();

    /**
     * The meta object literal for the '<em><b>Timeout</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MISSION__TIMEOUT = eINSTANCE.getMission_Timeout();

    /**
     * The meta object literal for the '{@link mars.rover.roverDSL.impl.IntegerImpl <em>Integer</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see mars.rover.roverDSL.impl.IntegerImpl
     * @see mars.rover.roverDSL.impl.RoverDSLPackageImpl#getInteger()
     * @generated
     */
    EClass INTEGER = eINSTANCE.getInteger();

    /**
     * The meta object literal for the '<em><b>Integer</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute INTEGER__INTEGER = eINSTANCE.getInteger_Integer();

    /**
     * The meta object literal for the '{@link mars.rover.roverDSL.impl.ColorImpl <em>Color</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see mars.rover.roverDSL.impl.ColorImpl
     * @see mars.rover.roverDSL.impl.RoverDSLPackageImpl#getColor()
     * @generated
     */
    EClass COLOR = eINSTANCE.getColor();

    /**
     * The meta object literal for the '<em><b>Color</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute COLOR__COLOR = eINSTANCE.getColor_Color();

    /**
     * The meta object literal for the '{@link mars.rover.roverDSL.MissionType <em>Mission Type</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see mars.rover.roverDSL.MissionType
     * @see mars.rover.roverDSL.impl.RoverDSLPackageImpl#getMissionType()
     * @generated
     */
    EEnum MISSION_TYPE = eINSTANCE.getMissionType();

    /**
     * The meta object literal for the '{@link mars.rover.roverDSL.Colors <em>Colors</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see mars.rover.roverDSL.Colors
     * @see mars.rover.roverDSL.impl.RoverDSLPackageImpl#getColors()
     * @generated
     */
    EEnum COLORS = eINSTANCE.getColors();

    /**
     * The meta object literal for the '{@link mars.rover.roverDSL.Safety <em>Safety</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see mars.rover.roverDSL.Safety
     * @see mars.rover.roverDSL.impl.RoverDSLPackageImpl#getSafety()
     * @generated
     */
    EEnum SAFETY = eINSTANCE.getSafety();

  }

} //RoverDSLPackage
