/*
 * generated by Xtext 2.23.0
 */
package mars.rover.serializer;

import com.google.inject.Inject;
import java.util.List;
import mars.rover.services.RoverDSLGrammarAccess;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.IGrammarAccess;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.nodemodel.INode;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.AbstractElementAlias;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.TokenAlias;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynNavigable;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynTransition;
import org.eclipse.xtext.serializer.sequencer.AbstractSyntacticSequencer;

@SuppressWarnings("all")
public class RoverDSLSyntacticSequencer extends AbstractSyntacticSequencer {

	protected RoverDSLGrammarAccess grammarAccess;
	protected AbstractElementAlias match_Mission_ColorsKeyword_10_0_q;
	protected AbstractElementAlias match_Mission_SensorsKeyword_11_0_q;
	
	@Inject
	protected void init(IGrammarAccess access) {
		grammarAccess = (RoverDSLGrammarAccess) access;
		match_Mission_ColorsKeyword_10_0_q = new TokenAlias(false, true, grammarAccess.getMissionAccess().getColorsKeyword_10_0());
		match_Mission_SensorsKeyword_11_0_q = new TokenAlias(false, true, grammarAccess.getMissionAccess().getSensorsKeyword_11_0());
	}
	
	@Override
	protected String getUnassignedRuleCallToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		return "";
	}
	
	
	@Override
	protected void emitUnassignedTokens(EObject semanticObject, ISynTransition transition, INode fromNode, INode toNode) {
		if (transition.getAmbiguousSyntaxes().isEmpty()) return;
		List<INode> transitionNodes = collectNodes(fromNode, toNode);
		for (AbstractElementAlias syntax : transition.getAmbiguousSyntaxes()) {
			List<INode> syntaxNodes = getNodesFor(transitionNodes, syntax);
			if (match_Mission_ColorsKeyword_10_0_q.equals(syntax))
				emit_Mission_ColorsKeyword_10_0_q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_Mission_SensorsKeyword_11_0_q.equals(syntax))
				emit_Mission_SensorsKeyword_11_0_q(semanticObject, getLastNavigableState(), syntaxNodes);
			else acceptNodes(getLastNavigableState(), syntaxNodes);
		}
	}

	/**
	 * Ambiguous syntax:
	 *     'Colors:'?
	 *
	 * This ambiguous syntax occurs at:
	 *     turndirection=STRING (ambiguity) 'Sensors:' sensorlist+=Sensors
	 *     turndirection=STRING (ambiguity) 'Sensors:'? 'End:' terminationcondition=STRING
	 */
	protected void emit_Mission_ColorsKeyword_10_0_q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     'Sensors:'?
	 *
	 * This ambiguous syntax occurs at:
	 *     colorlist+=Colors (ambiguity) 'End:' terminationcondition=STRING
	 *     turndirection=STRING 'Colors:'? (ambiguity) 'End:' terminationcondition=STRING
	 */
	protected void emit_Mission_SensorsKeyword_11_0_q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
}
