/*
 * generated by Xtext 2.23.0
 */
package mars.rover.ui;

import com.google.inject.Injector;
import mars.rover.ui.internal.RoverActivator;
import org.eclipse.core.runtime.Platform;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class RoverDSLExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Platform.getBundle(RoverActivator.PLUGIN_ID);
	}
	
	@Override
	protected Injector getInjector() {
		RoverActivator activator = RoverActivator.getInstance();
		return activator != null ? activator.getInjector(RoverActivator.MARS_ROVER_ROVERDSL) : null;
	}

}
