/*
 * generated by Xtext 2.23.0
 */
package mars.rover.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.EnumLiteralDeclaration;
import org.eclipse.xtext.EnumRule;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class RoverDSLGrammarAccess extends AbstractElementFinder.AbstractGrammarElementFinder {
	
	public class MissionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "mars.rover.RoverDSL.Mission");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cMissionKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cMissiontypeAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cMissiontypeMissionTypeEnumRuleCall_1_0 = (RuleCall)cMissiontypeAssignment_1.eContents().get(0);
		private final Group cGroup_2 = (Group)cGroup.eContents().get(2);
		private final Keyword cSafetyKeyword_2_0 = (Keyword)cGroup_2.eContents().get(0);
		private final Assignment cSafetypropertyAssignment_2_1 = (Assignment)cGroup_2.eContents().get(1);
		private final RuleCall cSafetypropertySafetyEnumRuleCall_2_1_0 = (RuleCall)cSafetypropertyAssignment_2_1.eContents().get(0);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cLakeColorsKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cLakelistAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cLakelistColorsEnumRuleCall_3_1_0 = (RuleCall)cLakelistAssignment_3_1.eContents().get(0);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cAvoidObjectsKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cObjectdistanceAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cObjectdistanceINTTerminalRuleCall_4_1_0 = (RuleCall)cObjectdistanceAssignment_4_1.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cBeginSentenceKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cBeginsentenceAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final RuleCall cBeginsentenceSTRINGTerminalRuleCall_5_1_0 = (RuleCall)cBeginsentenceAssignment_5_1.eContents().get(0);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cOuterBorderKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Assignment cBordercolorAssignment_6_1 = (Assignment)cGroup_6.eContents().get(1);
		private final RuleCall cBordercolorColorParserRuleCall_6_1_0 = (RuleCall)cBordercolorAssignment_6_1.eContents().get(0);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Keyword cForwardSpeedKeyword_7_0 = (Keyword)cGroup_7.eContents().get(0);
		private final Assignment cForwardspeedAssignment_7_1 = (Assignment)cGroup_7.eContents().get(1);
		private final RuleCall cForwardspeedINTTerminalRuleCall_7_1_0 = (RuleCall)cForwardspeedAssignment_7_1.eContents().get(0);
		private final Group cGroup_8 = (Group)cGroup.eContents().get(8);
		private final Keyword cReverseSpeedKeyword_8_0 = (Keyword)cGroup_8.eContents().get(0);
		private final Assignment cReversespeedAssignment_8_1 = (Assignment)cGroup_8.eContents().get(1);
		private final RuleCall cReversespeedINTTerminalRuleCall_8_1_0 = (RuleCall)cReversespeedAssignment_8_1.eContents().get(0);
		private final Group cGroup_9 = (Group)cGroup.eContents().get(9);
		private final Keyword cTurnDirectionKeyword_9_0 = (Keyword)cGroup_9.eContents().get(0);
		private final Assignment cTurndirectionAssignment_9_1 = (Assignment)cGroup_9.eContents().get(1);
		private final RuleCall cTurndirectionINTTerminalRuleCall_9_1_0 = (RuleCall)cTurndirectionAssignment_9_1.eContents().get(0);
		private final Group cGroup_10 = (Group)cGroup.eContents().get(10);
		private final Keyword cColorsKeyword_10_0 = (Keyword)cGroup_10.eContents().get(0);
		private final Assignment cColorlistAssignment_10_1 = (Assignment)cGroup_10.eContents().get(1);
		private final RuleCall cColorlistColorsEnumRuleCall_10_1_0 = (RuleCall)cColorlistAssignment_10_1.eContents().get(0);
		private final Keyword cEndKeyword_11 = (Keyword)cGroup.eContents().get(11);
		private final Assignment cTerminationconditionAssignment_12 = (Assignment)cGroup.eContents().get(12);
		private final RuleCall cTerminationconditionSTRINGTerminalRuleCall_12_0 = (RuleCall)cTerminationconditionAssignment_12.eContents().get(0);
		private final Group cGroup_13 = (Group)cGroup.eContents().get(13);
		private final Keyword cFlashingColorKeyword_13_0 = (Keyword)cGroup_13.eContents().get(0);
		private final Assignment cFlashingcolorAssignment_13_1 = (Assignment)cGroup_13.eContents().get(1);
		private final RuleCall cFlashingcolorColorsEnumRuleCall_13_1_0 = (RuleCall)cFlashingcolorAssignment_13_1.eContents().get(0);
		private final Group cGroup_14 = (Group)cGroup.eContents().get(14);
		private final Keyword cFinalSentenceKeyword_14_0 = (Keyword)cGroup_14.eContents().get(0);
		private final Assignment cFinalsentenceAssignment_14_1 = (Assignment)cGroup_14.eContents().get(1);
		private final RuleCall cFinalsentenceSTRINGTerminalRuleCall_14_1_0 = (RuleCall)cFinalsentenceAssignment_14_1.eContents().get(0);
		
		//Mission:
		//	'Mission:' missiontype=MissionType ('Safety:' safetyproperty=Safety)? ('LakeColors:' lakelist+=Colors*)?
		//	('AvoidObjects:' objectdistance=INT)? ('BeginSentence:' beginsentence=STRING)? ('OuterBorder:' bordercolor=Color)?
		//	('ForwardSpeed:' forwardspeed=INT)? ('ReverseSpeed:' reversespeed=INT)? ('TurnDirection:' turndirection=INT)?
		//	('Colors:' colorlist+=Colors*)?
		//	//('Sensors:' sensorlist += Sensors*)?
		//	'End:' terminationcondition=STRING ('FlashingColor:' flashingcolor=Colors)? ('FinalSentence:' finalsentence=STRING)? // For robot to say when mission is done. Maybe change final sentence to song? (validate options) Optional, default white
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//'Mission:' missiontype=MissionType ('Safety:' safetyproperty=Safety)? ('LakeColors:' lakelist+=Colors*)?
		//('AvoidObjects:' objectdistance=INT)? ('BeginSentence:' beginsentence=STRING)? ('OuterBorder:' bordercolor=Color)?
		//('ForwardSpeed:' forwardspeed=INT)? ('ReverseSpeed:' reversespeed=INT)? ('TurnDirection:' turndirection=INT)?
		//('Colors:' colorlist+=Colors*)? //('Sensors:' sensorlist += Sensors*)?
		//'End:' terminationcondition=STRING ('FlashingColor:' flashingcolor=Colors)? ('FinalSentence:' finalsentence=STRING)?
		public Group getGroup() { return cGroup; }
		
		//'Mission:'
		public Keyword getMissionKeyword_0() { return cMissionKeyword_0; }
		
		//missiontype=MissionType
		public Assignment getMissiontypeAssignment_1() { return cMissiontypeAssignment_1; }
		
		//MissionType
		public RuleCall getMissiontypeMissionTypeEnumRuleCall_1_0() { return cMissiontypeMissionTypeEnumRuleCall_1_0; }
		
		//('Safety:' safetyproperty=Safety)?
		public Group getGroup_2() { return cGroup_2; }
		
		//'Safety:'
		public Keyword getSafetyKeyword_2_0() { return cSafetyKeyword_2_0; }
		
		//safetyproperty=Safety
		public Assignment getSafetypropertyAssignment_2_1() { return cSafetypropertyAssignment_2_1; }
		
		//Safety
		public RuleCall getSafetypropertySafetyEnumRuleCall_2_1_0() { return cSafetypropertySafetyEnumRuleCall_2_1_0; }
		
		//('LakeColors:' lakelist+=Colors*)?
		public Group getGroup_3() { return cGroup_3; }
		
		//'LakeColors:'
		public Keyword getLakeColorsKeyword_3_0() { return cLakeColorsKeyword_3_0; }
		
		//lakelist+=Colors*
		public Assignment getLakelistAssignment_3_1() { return cLakelistAssignment_3_1; }
		
		//Colors
		public RuleCall getLakelistColorsEnumRuleCall_3_1_0() { return cLakelistColorsEnumRuleCall_3_1_0; }
		
		//('AvoidObjects:' objectdistance=INT)?
		public Group getGroup_4() { return cGroup_4; }
		
		//'AvoidObjects:'
		public Keyword getAvoidObjectsKeyword_4_0() { return cAvoidObjectsKeyword_4_0; }
		
		//objectdistance=INT
		public Assignment getObjectdistanceAssignment_4_1() { return cObjectdistanceAssignment_4_1; }
		
		//INT
		public RuleCall getObjectdistanceINTTerminalRuleCall_4_1_0() { return cObjectdistanceINTTerminalRuleCall_4_1_0; }
		
		//('BeginSentence:' beginsentence=STRING)?
		public Group getGroup_5() { return cGroup_5; }
		
		//'BeginSentence:'
		public Keyword getBeginSentenceKeyword_5_0() { return cBeginSentenceKeyword_5_0; }
		
		//beginsentence=STRING
		public Assignment getBeginsentenceAssignment_5_1() { return cBeginsentenceAssignment_5_1; }
		
		//STRING
		public RuleCall getBeginsentenceSTRINGTerminalRuleCall_5_1_0() { return cBeginsentenceSTRINGTerminalRuleCall_5_1_0; }
		
		//('OuterBorder:' bordercolor=Color)?
		public Group getGroup_6() { return cGroup_6; }
		
		//'OuterBorder:'
		public Keyword getOuterBorderKeyword_6_0() { return cOuterBorderKeyword_6_0; }
		
		//bordercolor=Color
		public Assignment getBordercolorAssignment_6_1() { return cBordercolorAssignment_6_1; }
		
		//Color
		public RuleCall getBordercolorColorParserRuleCall_6_1_0() { return cBordercolorColorParserRuleCall_6_1_0; }
		
		//('ForwardSpeed:' forwardspeed=INT)?
		public Group getGroup_7() { return cGroup_7; }
		
		//'ForwardSpeed:'
		public Keyword getForwardSpeedKeyword_7_0() { return cForwardSpeedKeyword_7_0; }
		
		//forwardspeed=INT
		public Assignment getForwardspeedAssignment_7_1() { return cForwardspeedAssignment_7_1; }
		
		//INT
		public RuleCall getForwardspeedINTTerminalRuleCall_7_1_0() { return cForwardspeedINTTerminalRuleCall_7_1_0; }
		
		//('ReverseSpeed:' reversespeed=INT)?
		public Group getGroup_8() { return cGroup_8; }
		
		//'ReverseSpeed:'
		public Keyword getReverseSpeedKeyword_8_0() { return cReverseSpeedKeyword_8_0; }
		
		//reversespeed=INT
		public Assignment getReversespeedAssignment_8_1() { return cReversespeedAssignment_8_1; }
		
		//INT
		public RuleCall getReversespeedINTTerminalRuleCall_8_1_0() { return cReversespeedINTTerminalRuleCall_8_1_0; }
		
		//('TurnDirection:' turndirection=INT)?
		public Group getGroup_9() { return cGroup_9; }
		
		//'TurnDirection:'
		public Keyword getTurnDirectionKeyword_9_0() { return cTurnDirectionKeyword_9_0; }
		
		//turndirection=INT
		public Assignment getTurndirectionAssignment_9_1() { return cTurndirectionAssignment_9_1; }
		
		//INT
		public RuleCall getTurndirectionINTTerminalRuleCall_9_1_0() { return cTurndirectionINTTerminalRuleCall_9_1_0; }
		
		//('Colors:' colorlist+=Colors*)?
		public Group getGroup_10() { return cGroup_10; }
		
		//'Colors:'
		public Keyword getColorsKeyword_10_0() { return cColorsKeyword_10_0; }
		
		//colorlist+=Colors*
		public Assignment getColorlistAssignment_10_1() { return cColorlistAssignment_10_1; }
		
		//Colors
		public RuleCall getColorlistColorsEnumRuleCall_10_1_0() { return cColorlistColorsEnumRuleCall_10_1_0; }
		
		////('Sensors:' sensorlist += Sensors*)?
		//'End:'
		public Keyword getEndKeyword_11() { return cEndKeyword_11; }
		
		//terminationcondition=STRING
		public Assignment getTerminationconditionAssignment_12() { return cTerminationconditionAssignment_12; }
		
		//STRING
		public RuleCall getTerminationconditionSTRINGTerminalRuleCall_12_0() { return cTerminationconditionSTRINGTerminalRuleCall_12_0; }
		
		//('FlashingColor:' flashingcolor=Colors)?
		public Group getGroup_13() { return cGroup_13; }
		
		//'FlashingColor:'
		public Keyword getFlashingColorKeyword_13_0() { return cFlashingColorKeyword_13_0; }
		
		//flashingcolor=Colors
		public Assignment getFlashingcolorAssignment_13_1() { return cFlashingcolorAssignment_13_1; }
		
		//Colors
		public RuleCall getFlashingcolorColorsEnumRuleCall_13_1_0() { return cFlashingcolorColorsEnumRuleCall_13_1_0; }
		
		//('FinalSentence:' finalsentence=STRING)?
		public Group getGroup_14() { return cGroup_14; }
		
		//'FinalSentence:'
		public Keyword getFinalSentenceKeyword_14_0() { return cFinalSentenceKeyword_14_0; }
		
		//finalsentence=STRING
		public Assignment getFinalsentenceAssignment_14_1() { return cFinalsentenceAssignment_14_1; }
		
		//STRING
		public RuleCall getFinalsentenceSTRINGTerminalRuleCall_14_1_0() { return cFinalsentenceSTRINGTerminalRuleCall_14_1_0; }
	}
	public class ColorElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "mars.rover.RoverDSL.Color");
		private final Assignment cColorAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cColorColorsEnumRuleCall_0 = (RuleCall)cColorAssignment.eContents().get(0);
		
		////Colors: color = STRING;
		////Sensors: sensor = STRING;
		//Color:
		//	color=Colors;
		@Override public ParserRule getRule() { return rule; }
		
		//color=Colors
		public Assignment getColorAssignment() { return cColorAssignment; }
		
		//Colors
		public RuleCall getColorColorsEnumRuleCall_0() { return cColorColorsEnumRuleCall_0; }
	}
	
	public class MissionTypeElements extends AbstractElementFinder.AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "mars.rover.RoverDSL.MissionType");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cAvoidColorsEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cAvoidColorsAvoidColorsKeyword_0_0 = (Keyword)cAvoidColorsEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cFindColorsEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cFindColorsFindColorsKeyword_1_0 = (Keyword)cFindColorsEnumLiteralDeclaration_1.eContents().get(0);
		
		//enum MissionType:
		//	AvoidColors | FindColors;
		public EnumRule getRule() { return rule; }
		
		//AvoidColors | FindColors
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//AvoidColors
		public EnumLiteralDeclaration getAvoidColorsEnumLiteralDeclaration_0() { return cAvoidColorsEnumLiteralDeclaration_0; }
		
		//"AvoidColors"
		public Keyword getAvoidColorsAvoidColorsKeyword_0_0() { return cAvoidColorsAvoidColorsKeyword_0_0; }
		
		//FindColors
		public EnumLiteralDeclaration getFindColorsEnumLiteralDeclaration_1() { return cFindColorsEnumLiteralDeclaration_1; }
		
		//"FindColors"
		public Keyword getFindColorsFindColorsKeyword_1_0() { return cFindColorsFindColorsKeyword_1_0; }
	}
	public class ColorsElements extends AbstractElementFinder.AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "mars.rover.RoverDSL.Colors");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cWhiteEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cWhiteWhiteKeyword_0_0 = (Keyword)cWhiteEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cRedEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cRedRedKeyword_1_0 = (Keyword)cRedEnumLiteralDeclaration_1.eContents().get(0);
		private final EnumLiteralDeclaration cBlueEnumLiteralDeclaration_2 = (EnumLiteralDeclaration)cAlternatives.eContents().get(2);
		private final Keyword cBlueBlueKeyword_2_0 = (Keyword)cBlueEnumLiteralDeclaration_2.eContents().get(0);
		private final EnumLiteralDeclaration cYellowEnumLiteralDeclaration_3 = (EnumLiteralDeclaration)cAlternatives.eContents().get(3);
		private final Keyword cYellowYellowKeyword_3_0 = (Keyword)cYellowEnumLiteralDeclaration_3.eContents().get(0);
		private final EnumLiteralDeclaration cBlackEnumLiteralDeclaration_4 = (EnumLiteralDeclaration)cAlternatives.eContents().get(4);
		private final Keyword cBlackBlackKeyword_4_0 = (Keyword)cBlackEnumLiteralDeclaration_4.eContents().get(0);
		
		//enum Colors:
		//	White | Red | Blue | Yellow | Black;
		public EnumRule getRule() { return rule; }
		
		//White | Red | Blue | Yellow | Black
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//White
		public EnumLiteralDeclaration getWhiteEnumLiteralDeclaration_0() { return cWhiteEnumLiteralDeclaration_0; }
		
		//"White"
		public Keyword getWhiteWhiteKeyword_0_0() { return cWhiteWhiteKeyword_0_0; }
		
		//Red
		public EnumLiteralDeclaration getRedEnumLiteralDeclaration_1() { return cRedEnumLiteralDeclaration_1; }
		
		//"Red"
		public Keyword getRedRedKeyword_1_0() { return cRedRedKeyword_1_0; }
		
		//Blue
		public EnumLiteralDeclaration getBlueEnumLiteralDeclaration_2() { return cBlueEnumLiteralDeclaration_2; }
		
		//"Blue"
		public Keyword getBlueBlueKeyword_2_0() { return cBlueBlueKeyword_2_0; }
		
		//Yellow
		public EnumLiteralDeclaration getYellowEnumLiteralDeclaration_3() { return cYellowEnumLiteralDeclaration_3; }
		
		//"Yellow"
		public Keyword getYellowYellowKeyword_3_0() { return cYellowYellowKeyword_3_0; }
		
		//Black
		public EnumLiteralDeclaration getBlackEnumLiteralDeclaration_4() { return cBlackEnumLiteralDeclaration_4; }
		
		//"Black"
		public Keyword getBlackBlackKeyword_4_0() { return cBlackBlackKeyword_4_0; }
	}
	public class SafetyElements extends AbstractElementFinder.AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "mars.rover.RoverDSL.Safety");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cOnEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cOnOnKeyword_0_0 = (Keyword)cOnEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cOffEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cOffOffKeyword_1_0 = (Keyword)cOffEnumLiteralDeclaration_1.eContents().get(0);
		
		//enum Safety:
		//	On | Off;
		public EnumRule getRule() { return rule; }
		
		//On | Off
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//On
		public EnumLiteralDeclaration getOnEnumLiteralDeclaration_0() { return cOnEnumLiteralDeclaration_0; }
		
		//"On"
		public Keyword getOnOnKeyword_0_0() { return cOnOnKeyword_0_0; }
		
		//Off
		public EnumLiteralDeclaration getOffEnumLiteralDeclaration_1() { return cOffEnumLiteralDeclaration_1; }
		
		//"Off"
		public Keyword getOffOffKeyword_1_0() { return cOffOffKeyword_1_0; }
	}
	
	private final MissionElements pMission;
	private final MissionTypeElements eMissionType;
	private final ColorElements pColor;
	private final ColorsElements eColors;
	private final SafetyElements eSafety;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public RoverDSLGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pMission = new MissionElements();
		this.eMissionType = new MissionTypeElements();
		this.pColor = new ColorElements();
		this.eColors = new ColorsElements();
		this.eSafety = new SafetyElements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("mars.rover.RoverDSL".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//Mission:
	//	'Mission:' missiontype=MissionType ('Safety:' safetyproperty=Safety)? ('LakeColors:' lakelist+=Colors*)?
	//	('AvoidObjects:' objectdistance=INT)? ('BeginSentence:' beginsentence=STRING)? ('OuterBorder:' bordercolor=Color)?
	//	('ForwardSpeed:' forwardspeed=INT)? ('ReverseSpeed:' reversespeed=INT)? ('TurnDirection:' turndirection=INT)?
	//	('Colors:' colorlist+=Colors*)?
	//	//('Sensors:' sensorlist += Sensors*)?
	//	'End:' terminationcondition=STRING ('FlashingColor:' flashingcolor=Colors)? ('FinalSentence:' finalsentence=STRING)? // For robot to say when mission is done. Maybe change final sentence to song? (validate options) Optional, default white
	//;
	public MissionElements getMissionAccess() {
		return pMission;
	}
	
	public ParserRule getMissionRule() {
		return getMissionAccess().getRule();
	}
	
	//enum MissionType:
	//	AvoidColors | FindColors;
	public MissionTypeElements getMissionTypeAccess() {
		return eMissionType;
	}
	
	public EnumRule getMissionTypeRule() {
		return getMissionTypeAccess().getRule();
	}
	
	////Colors: color = STRING;
	////Sensors: sensor = STRING;
	//Color:
	//	color=Colors;
	public ColorElements getColorAccess() {
		return pColor;
	}
	
	public ParserRule getColorRule() {
		return getColorAccess().getRule();
	}
	
	//enum Colors:
	//	White | Red | Blue | Yellow | Black;
	public ColorsElements getColorsAccess() {
		return eColors;
	}
	
	public EnumRule getColorsRule() {
		return getColorsAccess().getRule();
	}
	
	//enum Safety:
	//	On | Off;
	public SafetyElements getSafetyAccess() {
		return eSafety;
	}
	
	public EnumRule getSafetyRule() {
		return getSafetyAccess().getRule();
	}
	
	//terminal ID:
	//	'^'? ('a'..'z' | 'A'..'Z' | '_') ('a'..'z' | 'A'..'Z' | '_' | '0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt:
	//	'0'..'9'+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//	'"' ('\\' . | !('\\' | '"'))* '"' |
	//	"'" ('\\' . | !('\\' | "'"))* "'";
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT:
	//	'/*'->'*/';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT:
	//	'//' !('\n' | '\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS:
	//	' ' | '\t' | '\r' | '\n'+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER:
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
