/*
 * generated by Xtext 2.23.0
 */
package mars.rover.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import mars.rover.RoverDSLRuntimeModule;
import mars.rover.RoverDSLStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class RoverDSLIdeSetup extends RoverDSLStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new RoverDSLRuntimeModule(), new RoverDSLIdeModule()));
	}
	
}
