/**
 * generated by Xtext 2.23.0
 */
package mars.rover.generator;

import mars.rover.generator.PythonGeneratorM;
import mars.rover.generator.PythonGeneratorS;
import mars.rover.roverDSL.Mission;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.resource.Resource;
import org.eclipse.xtext.generator.AbstractGenerator;
import org.eclipse.xtext.generator.IFileSystemAccess2;
import org.eclipse.xtext.generator.IGeneratorContext;
import org.eclipse.xtext.xbase.lib.IteratorExtensions;

/**
 * Generates code from your model files on save.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#code-generation
 */
@SuppressWarnings("all")
public class RoverDSLGenerator extends AbstractGenerator {
  @Override
  public void doGenerate(final Resource resource, final IFileSystemAccess2 fsa, final IGeneratorContext context) {
    EObject _head = IteratorExtensions.<EObject>head(resource.getAllContents());
    final Mission root = ((Mission) _head);
    if ((root != null)) {
      fsa.generateFile("master.py", PythonGeneratorM.toText(root));
      fsa.generateFile("slave.py", PythonGeneratorS.toText(root));
    }
  }
}
