/*
 * generated by Xtext 2.23.0
 */
package mars.rover;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class RoverDSLStandaloneSetup extends RoverDSLStandaloneSetupGenerated {

	public static void doSetup() {
		new RoverDSLStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
