/*
 * generated by Xtext 2.23.0
 */
package mars.rover.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractRoverDSLScopeProvider extends DelegatingScopeProvider {
}
